baseurl = "https://yukaibackpacking.netlify.app"
title = "YuKai Blog"
languageCode = "en-us"
disqusShortname = "yukai"
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 7 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  author = "YuKai"
  header_image = "/img/homee.jpg"
  SEOTitle = "Yukaibackpacking Blog"
  description = "YuKai，資訊系學生，生活探險家 | 走在江湖，總得有個硬實力技術"
  keyword = "YuKai, yukaibackpacking, software engineering, 軟體工程, 背包旅行" 
  slogan = ["機不可失，失不再來",
            "藤枝必亡，但朽木終將重生", 
            "怕走崎嶇路，莫想登高峰", 
            "新技術永遠不嫌多",
            "無火不起煙，無風不起浪，事出必有因"]

  image_404 = "/img/404.jpg"
  title_404 = "你的技術大背炸了 :( 但給你一隻貓貓安慰你 :)"
  omit_categories = false
  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = "U1TNM0W5FT"
  algolia_indexName = "dev_blog"
  algolia_apiKey = "e6cab1e9fc60314eb98f7f860bd1a6e2"

  # Sidebar settings
  sidebar_about_description = "IT Student, Open Source and Life Adventurer"
  sidebar_avatar = "element/cabbageWorm.jpeg"

  featured_tags = true 
  featured_condition_size = 0 

  # Baidu Analytics
  ba_track_id = ""
  
  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false
  friends = false
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  custom_css = ["css/addones.css"]
  custom_js = ["js/sideLinks.js", "js/addones.min.js"]

  [params.social]
  email          = "marvelo.k0515@gmail.com"
  facebook      = "https://www.facebook.com/profile.php?id=100009946749327"
  instagram     = "https://www.instagram.com/yukai8765/"
  github         = "https://github.com/Kevin051596"
  discord = "https://discordapp.com/users/640102516738097163"
  
  [[params.friend_link]]
  title = ""
  href =  ""

  [[params.bookmark_link]]
  title =  ""
  href =  ""
  
  [[params.addtional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"
  [[params.addtional_menus]]
  title =  "NOTES"
  href =  "/notes/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
